[package]
name = "untitled_laser_project"
version = "0.1.0"
authors = [ "Jeremy Day <jadaytime@gmail.com>" ]
edition = "2018"

[dependencies]
amethyst = "0.12.0"
rand = "0.7"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
