[package]
name = "lase"
version = "0.4.1"
authors = [ "Jeremy Day <jadaytime@gmail.com>" ]
edition = "2018"

[dependencies]
amethyst = "0.13"
nalgebra = "0.18"
rand = "0.7"
serde = "1.0"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
